### ISSUE TITLE
Questions and Clarifications: IPv6, Clone Location, and Repository Content

### ISSUE THREAD

**Issue by Depfrost** [springcomp/self-hosted-simplelogin#5]
Hi, 

I am trying to run this project using a pre-existing network and named volumes. I have some questions:

1. About the IPv6 mentioned in the readme, can the project work without it ?
2. Is it required to clone it in `/opt/simplelogin`, or can I clone it in my home directory?
3. The file `postfix/conf.d/virtual` shouldn't be present in the repository, correct ?

Thank you for your assistance with this matter and for sharing this cool version of simple login.

**Comment by springcomp** [comment]
Hi @Depfrost thanks for your feedback and for your interest in this project.

IPv6 is configured for the web application. It is optional of course.
SimpleLogin mail server does not support IPv6 anyway.

I think the target folder to clone the project is not important. I just had a quick look and did not notice any configurations that assumed that location.

Finally, the `virtual` file is a simple example that I used in my scenarios so I wanted to keep the syntax handy. This file is referred to on startup and from the postfix configuration file so at the minimum you need to have an empty file I guess.

**Comment by Depfrost** [comment]
Thank you for your prompt response.
It's good to know that the project can work without IPv6 and that the choice of the target folder is not critical.

About the "virtual" file, I noticed the script "up.sh" attempts to generate this file at startup if it does not exist:
```
if [ ! -f ./postfix/conf.d/virtual ]; then
  sed -e "s/domain.tld/${DOMAIN}/g" ./postfix/conf.d/virtual.tpl > ./postfix/conf.d/virtual
fi
```
So if this file already exists, I just need to make sure it contains the correct domain name.

With all the details you provided, I consider this issue resolved, and I will go ahead and close it.

Once again, thank you for your assistance and for sharing this much-needed version of SimpleLogin.
